---
title: Background Materials
---

The goal of the Active Acoustics Strategic Initiative (AA-SI) includes organizing and standardizing multi-frequency and wide-bandwidth echosounder data to enable efficient data processing and analysis in a cloud environment. This is a summary and links to additional background information on how active acoustics are used to study fish and zooplankton in the ocean, the types of equipment commonly deployed to collect the data, common data formats, and requirements for data standardization.

# Website Background Reading Materials

[Discovery of Sound in the Ocean: How sound is used to locate fish (University of Rhode Island)](https://dosits.org/people-and-sound/fishing/how-is-sound-used-to-locate-fish/)

[Understanding Water-Column Sonar Data (NCEI)](https://storymaps.arcgis.com/stories/e245977def474bdba60952f30576908f)

## Active Acoustic Data Applications within NOAA

NOAA Fisheries is charged with conducting stock assessments of commercially-important species of fish, and frequently uses acoustic-trawl survey methods to accomplish this.

-   The AFSC surveys [pollock in Alaska](https://www.fisheries.noaa.gov/s3//2025-03/midwater-assessment-conservation-engineering-flyer.pdf)
-   The SWFSC surveys [coastal pelagic species on the West Coast](https://nmfs-swfsc-ast.github.io/echo-class/)
-   The NWFSC surveys [Pacific hake on the U.S. and Canada West Coasts](https://www.fisheries.noaa.gov/west-coast/science-data/joint-us-canada-integrated-ecosystem-and-pacific-hake-acoustic-trawl-survey)
-   The PIFSC collects ecosystem and oceanography data from various [research surveys in the Pacific Ocean near the Pacific Islands](https://www.fisheries.noaa.gov/pacific-islands/science-data/research-surveys-pacific#ecosystem-and-oceanography-surveys%C2%A0)
-   The NEFSC conducts [ecosystem surveys on the U.S. East Coast](https://www.fisheries.noaa.gov/about/northeast-ecosystems-surveys)
-   The SEFSC [surveys commercial and recreational fish in the Southeast Atlantic and Gulf of America (formerly Gulf of Mexico)](https://www.fisheries.noaa.gov/science-data/southeast-science-surveys-and-research#fish-research)

## Acoustic Instruments

Scientific echosounders record data to manufacturer-specified binary formats. The AA-SI works primarily with Kongsberg EK echosounders and data, but there are other echosounder manufacturers whose data we may use. We will update this site as we add other data sources.

In addition to the active acoustic data, we often work with user annotations, metadata, and contextual data including biological, oceanographic, meteorological, and benthic and pelagic habitat information to refine and improve echo classification.

### EK80

The [EK80](https://www.kongsberg.com/discovery/ocean-science/ek-family/ek80/) is the latest in the Kongsberg line of scientific echosounders. All NOAA Ships collect data using the EK80. "EK80" refers to the echosounder, which is the term used to describe the combination of a transducer, which is an instrument that generates an electrical signal that is transmitted into the water, and the transceiver, which is the instrument that receives the electrical signal (voltage) or "echo" from the water and digitizes it using acquisition software. 

The EK80 has several echosounders that can be used. The shipboard echosounder is called a Wide-Band Transceiver (WBT), and portable units are WBT-Tubes or WBATs (Wide-Band Autonomous Transceivers).

### EK60

The [EK60](https://www.kongsberg.com/discovery/products/discontinued/simrad-ek60/) is the previous generation scientific echosounder. It was introduced in the late 1990s, and was installed on NOAA Ships in the early 2000s. The majority of historic data collected by NOAA is from the EK60. 

The echosounder was called the General Purpose Transceiver (GPT) and the data acquisition software was called "ER60". The current EK80 software can control both WBTs and GPTs. 

Which software, ER60 or EK80, recorded the data is important to distinguish because the digital format of the data are different depending on software version.

### EK500

The [EK500](https://support.echoview.com/WebHelp/Reference/Echosounder_Configuration/EK500_configuration.htm) was used from the 1980s until the early 2000s on NOAA Ships. The AA-SI is focusing initially on EK80 and EK60 data formats, but may use some historical EK500 datasets in the future.

## Annotation Data

Most of the active acoustic data collection during NOAA Fisheries surveys are currently processed using [Echoview](https://echoview.com/solutions/marine/). This user-friendly software allows individuals to mark echograms with details about fish schools of interest, and add notes that relate marks, or regions, to contextual information including trawl data, camera footage, or seafloor bottom. Find out more about the active acoustic annotations [here].

## Metadata

Find out more about metadata formats [here](https://github.com/nmfs-ost/AA-SI_metadata).

Also, our collaborators at UW-APL ([Echospace](https://uw-echospace.github.io/)) have proposed set of specifications of data processing levels for acoustic data, which you can read about here [here](https://echolevels.readthedocs.io/en/latest/)

## Processing acoustic data using open science

A lot of work has gone into developing [echopype](https://echopype.readthedocs.io/en/latest/), which is a python package built to "enable interoperability and scalability in ocean sonar data processing". The AA-SI will rely on echopype for a lot of NOAA's efforts to transition to using open source tools to process acoustic data. The UW-APL Echospace team's [echopype website](https://echopype.readthedocs.io/en/latest/) is a great place to get up to speed with this powerful package.
